version: '3.7'


services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
          - SECRET_KEY=n23&0b)0m1h%7ovg^5v(n1j8=xg@c&8jf-xc7!_rmi%m*=xt#*
          - DEBUG=True
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
#            - db
            - broker
            - redis

#    db:
#        image: postgres:11
#        volumes:
#            - postgres_data:/var/lib/postgresql/data/
#        environment:
#            - "POSTGRES_HOST_AUTH_METHOD=trust"


    broker:
        image: rabbitmq:latest
        hostname: broker
        environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=mypass
        ports:
          - "5672:5672"

    worker:
        build: .
        restart: "no"
        command: celery -A myshop worker -l info
        volumes:
          - .:/code
        depends_on:
          - broker

    flower:
        image: mher/flower
        command: ["flower", "--broker=amqp://admin:mypass@broker", "--port=5555"]
        ports:
          - 5555:5555
        depends_on:
          - broker

    redis:
        image: redis:latest
        hostname: redis
        ports:
          - 127.0.0.1:6379:6379
        volumes:
          - redisdata:/data

volumes:
    redisdata:
#    postgres_data:
